package bg.softuni.human_resource_managements.model.enums;

public enum PositionName {
    CHIEF_EXECUTIVE_OFFICER,
    CHIEF_OPERATING_OFFICER,
    CHIEF_FINANCIAL_OFFICER,
    FINANCIAL_OFFICER,
    HUMAN_RESOURCES_MANAGER,
    HEAD_OF_DEPARTMENT,
    IT_ADMINISTRATOR,
    PROJECT_MANAGER,
    MARKETING_MANAGER,
    DEVELOPER,
    SENIOR_DEVELOPER,
    LEAD_DEVELOPER,
    QUALITY_ASSURANCE,
    CUSTOMER_SUPPORT,
    CLEANER
}
